const {test}=require('node:test');
const assert=require('node:assert/strict');
const C=require('../app/core.js');
const base={attack:100,defense:100,maxHp:1000,speed:100,critRate:.1,critPower:.5,debuffEnhance:0,debuffResist:0};
const roster=['1','2'].map(id=>({id,name:'测试式神'+id,assets:{baseAttrs40:{0:base,1:base}}}));
const hero=(heroId=1,extra={})=>({heroId,level:40,star:6,awake:1,skinfo:[[1003,5],[1001,1],[1002,4]],...extra});
const raw=(extra={})=>({format:'mumu-snapshot-v1',completeness:'complete',capturedAt:'2026-09-12',player:{serverId:1,shortId:2,name:'合成测试'},heroes:{a:hero(1),b:hero(2)},hero_equips:Array.from({length:6},(_,i)=>({id:'s'+i,slot:i+1,quality:6,level:15,setId:'测试套装',mainAttrType:'attack_flat',mainAttrValue:10,subAttributes:[]})),equipPresets:[],...extra});
const cfg=(extra={})=>({suitRequirements:[],suitSelectionComplete:true,ranges:[],mainStats:{},scope:'all',metricId:1,sixStarOnly:true,maxLevelOnly:true,...extra});
const member=(sid='1',extra={})=>({index:0,kind:'shikigami',shikigamiId:sid,name:'测试式神'+sid,awakening:1,skills:[],config:cfg(),...extra});
const lineup=(members=[member()],extra={})=>({title:'合成计算案例',members,requirementsComplete:true,...extra});
test('删除预设和自建阵容后，重启与预设内容更新不会恢复；可以主动重新添加',()=>{
 const presets=[{id:'preset-a',code:'|TA|a',title:'预设 A'},{id:'preset-b',code:'|TA|b',title:'预设 B'}];
 const state={schemaVersion:1,lineups:[{...presets[0],title:'已编辑 A'},{id:'user-c',code:'|TA|c'}],accounts:[]},before=JSON.stringify(state);
 const removed=C.removeLibraryLineups(state,presets,['preset-a','user-c']);
 assert.equal(JSON.stringify(state),before);assert.deepEqual(removed.deletedPresetIds,['preset-a']);
 const restored=JSON.parse(JSON.stringify(removed)),updated=presets.map(l=>({...l,title:'更新后的预设'}));
 assert.deepEqual(C.libraryLineups(updated,restored).map(l=>l.id),['preset-b']);
 assert.deepEqual(C.removeLibraryLineups(restored,updated,['preset-a']).deletedPresetIds,['preset-a']);
 restored.lineups.push({...presets[0],id:'user-readded'});
 assert.equal(C.libraryLineups(updated,restored).filter(l=>l.code==='|TA|a').length,1);
 restored.lineups=[presets[0]];assert.equal(C.libraryLineups(updated,restored).filter(l=>l.code==='|TA|a').length,1);
});
test('预设补齐解析内容仍保留失效证据；旧备份与删除记录校验',()=>{
 const preset={id:'p',code:'|TA|a',members:[member()],decodeState:'decoded-server'},failure={kind:'expired-code',serverCode:31279};
 const state={lineups:[{id:'p',code:'|TA|a',members:[],lastParseError:'已过期',lastParseFailure:failure}]};
 const result=C.libraryLineups([preset],state)[0];
 assert.equal(result.members.length,1);assert.equal(result.lastParseFailure.serverCode,31279);assert.equal(result.lastParseError,'已过期');
 assert.deepEqual(C.deletedPresetIds(undefined),[]);assert.deepEqual(C.deletedPresetIds(['p','p']),['p']);
 for(const bad of [null,'p',[42],[''],['a\nb']])assert.throws(()=>C.deletedPresetIds(bad),/删除记录/);
});
test('短码保持原分隔符并支持不透明键和完整内容大小边界',()=>{const code='|TA|'+'a'.repeat(32);assert.equal(C.normalizeCode('\uFEFF '+code+'\n'),code);assert.equal(C.classifyCode(code),'pipe-ta');assert.equal(C.classifyCode('|TA|opaque-key'),'pipe-ta');assert.equal(C.classifyCode('文字'+code),'unknown');assert.equal(C.classifyCode('#TA#payload'),'hash-ta');assert.equal(C.classifyCode('a'.repeat(32*1024*1024+1)),'too-large');});
test('响应必须是真成功，损坏结构不得生成展示阵容',()=>{assert.throws(()=>C.adaptInspection({ok:false,error:'阵容码不是有效的 Base64'}));assert.throws(()=>C.adaptInspection({ok:true,data:{}}));});
test('API槽位关联保留重复式神和无御魂阴阳师',()=>{const payload={ok:true,data:{slotCount:3,occupiedSlots:3,entities:[{index:0,kind:'shikigami',occupied:true,shikigamiId:1},{index:1,kind:'shikigami',occupied:true,shikigamiId:1},{index:2,kind:'onmyoji',occupied:true}],editableTargets:[{entityIndex:1,shikigamiId:1,...cfg()}]}};const l=C.adaptInspection(payload,roster);assert.equal(l.members.length,3);assert.equal(l.members[0].config,null);assert.equal(l.members[1].config.entityIndex,1);assert.equal(l.members[2].kind,'onmyoji');payload.data.editableTargets[0].shikigamiId=2;assert.throws(()=>C.adaptInspection(payload,roster));});
test('平安志技能按技能ID处理，不依赖数组顺序',()=>{const a=C.parseAccount(raw());assert.equal(Object.keys(a.heroes).length,2);assert.equal(C.memberCandidates(member('1',{skills:[{id:1002,level:4,exact:true}]}),a).status,'found');assert.equal(C.memberCandidates(member('1',{skills:[{id:1002,level:5}]}),a).status,'missing');});
test('重复御魂ID与损坏技能拒绝导入',()=>{const a=raw();a.hero_equips.push(a.hero_equips[0]);assert.throws(()=>C.parseAccount(a),/重复/);assert.throws(()=>C.parseAccount(raw({heroes:{a:hero(1,{skinfo:[[1001,'bad']]})}})),/技能/);});
test('快照替换与增量合并按实例ID，合并备份可恢复',()=>{const old=C.parseAccount(raw());const incoming=C.parseAccount(raw({heroes:{a:hero(1,{level:39})},hero_equips:[]}));const merged=C.mergeAccount(old,incoming);assert.equal(Object.keys(merged.heroes).length,2);assert.equal(merged.heroes.a.level,39);assert.equal(Object.keys(merged.souls).length,6);const restored=C.restoreAccount(JSON.parse(JSON.stringify(merged)));assert.equal(restored.merged,true);assert.equal(Object.keys(restored.heroes).length,2);assert.equal(Object.keys(restored.souls).length,6);assert.equal(Object.keys(incoming.heroes).length,1);});
test('未知等级星级不套用40级6星面板，导出attrs不猜单位',()=>{assert.equal(C.baseFromRoster({shikigamiId:'1',level:39,star:6,awake:1},roster),null);assert.equal(C.baseFromRoster(C.parseAccount(raw()).heroes.a,roster).critDamage,1.5);});
test('御魂百分比、固定值、两件加成与额外攻击顺序',()=>{const b={attack:1000,hp:10000,defense:500,speed:100,crit:.1,critDamage:1.5,effectHit:0,effectResist:0};const souls=[{set:'攻击套',stats:{attackPercent:.55,attack:100,speed:20}},{set:'攻击套',stats:{crit:.3}}];const p=C.panel(b,souls,[{name:'攻击加成',stat:'attackPercent',value:.15,suitNames:['攻击套']}],{attackPercent:.2,attack:50,critDamage:.4}).values;assert.equal(p.attack,2210);assert.equal(p.speed,120);assert.equal(p.crit,.4);assert.equal(p.critDamage,1.9);assert.equal(C.score(p,1),4199);assert.equal(C.score(p,11),0);});
test('范围百分数除100一次，阈值边界包含',()=>{assert.deepEqual(C.checkPanel({crit:1,speed:150,attack:200,critDamage:2},cfg({ranges:[{stat:'crit',min:100,percentage:true},{stat:'speed',min:150,max:150}],targetScore:400})),[]);assert.equal(C.checkPanel({crit:.99},cfg({ranges:[{stat:'crit',min:100,percentage:true}]})).length,1);});
test('小仓库可证明符合已知要求并给出6个不同御魂',()=>{const a=C.parseAccount(raw());const result=C.matchLineup(lineup(),a,roster,[]);assert.equal(result.status,'available');assert.equal(new Set(result.assignment[0].soulIds).size,6);assert.equal(result.assignment[0].panel.attack,160);});
test('同一套御魂不能同时分给两个成员',()=>{const a=C.parseAccount(raw());const result=C.matchLineup(lineup([member('1'),member('2',{index:1})]),a,roster,[]);assert.equal(result.status,'unknown');assert.equal(result.assignment,null);assert.match(result.reasons.join(' '),/冲突/);});
test('两套御魂全队分配无重叠',()=>{const r=raw();r.hero_equips.push(...r.hero_equips.map(q=>({...q,id:'t'+q.id})));const result=C.matchLineup(lineup([member('1'),member('2',{index:1})]),C.parseAccount(r),roster,[],{limit:1000});assert.equal(result.status,'available');assert.equal(new Set(result.assignment.flatMap(b=>b.soulIds)).size,12);});
test('两只同类型需求必须有两个实例',()=>{const result=C.matchLineup(lineup([member(),member('1',{index:1})]),C.parseAccount(raw()),roster,[]);assert.equal(result.status,'missing');assert.match(result.reasons[0],/2个不同实例/);});
test('受限搜索未命中不能证明做不出',()=>{const a=C.parseAccount(raw());const r=C.findBuilds(a.heroes.a,cfg({ranges:[{stat:'attack',min:999999}]}),a,roster,[],{limit:0,width:2});assert.equal(r.status,'unknown');assert.equal(r.exhaustive,false);});
test('缺少指定套装能报告库存缺口',()=>{const a=C.parseAccount(raw());assert.equal(C.findBuilds(a.heroes.a,cfg({suitRequirements:[{name:'不存在套装',count:4}]}),a,roster,[]).status,'missing');});
test('未识别御魂/不完整导出不作不存在的证明',()=>{const a=C.parseAccount(raw({completeness:'partial',heroes:{},hero_equips:[]}));assert.equal(C.matchLineup(lineup(),a,roster,[]).status,'unknown');const b=raw();b.hero_equips[0].mainAttrType='future-stat';const parsed=C.parseAccount(b);assert.equal(C.findBuilds(parsed.heroes.a,cfg(),parsed,roster,[]).status,'unknown');});
test('未知两件套值、负额外属性、最高属性约束保持未知',()=>{const a=C.parseAccount(raw());for(const c of [cfg({highestStat:'attack'}),cfg({extraAttributes:{critDamage:-.2}}),cfg({scope:'unequipped'})])assert.equal(C.findBuilds(a.heroes.a,c,a,roster,[]).status,'unknown');assert.equal(C.findBuilds(a.heroes.a,cfg(),a,roster,[{name:'未知值',stat:'critDamage',value:null,suitNames:['测试套装']}]).status,'unknown');});
test('未知觉醒、技能和增量快照仍不能判为全队可组成',()=>{const a=C.parseAccount(raw());for(const l of [lineup([member('1',{awakening:null})]),lineup([member('1',{skills:null})]),lineup(undefined,{requirementsComplete:false})])assert.equal(C.matchLineup(l,a,roster,[]).status,'unknown');assert.equal(C.matchLineup(lineup(),{...a,merged:true},roster,[]).status,'unknown');});
test('本地配置校验拒绝非法技能、Infinity和反向区间',()=>{assert.throws(()=>C.validateLineup(lineup([member('1',{skills:[{id:'<img>',level:5}]})])));assert.throws(()=>C.validateLineup(lineup([member('1',{config:cfg({extraAttributes:{attack:Infinity}})})])));assert.throws(()=>C.validateLineup(lineup([member('1',{config:cfg({ranges:[{stat:'speed',min:200,max:100}]})})])));assert.equal(C.validateLineup(lineup()).members[0].shikigamiId,'1');});
test('协战需求不能误报账号缺式神',()=>{const a=C.parseAccount(raw({heroes:{}}));const r=C.matchLineup(lineup([member('1',{borrowed:true})]),a,roster,[]);assert.equal(r.status,'unknown');assert.match(r.reasons.join(' '),/借用/);});
