const fs=require('node:fs');
const crypto=require('node:crypto');
const path=require('node:path');
const asar=require('@electron/asar');
const archive='release/win-unpacked/resources/app.asar';
const files=asar.listPackage(archive).map(p=>p.replaceAll('\\','/'));
const forbidden=files.filter(p=>/平安志示例数据|\.xlsx$|\/(tests|tools|user-data|private|ta-python)\/|web-sources\.json$|decoded\.json$/.test(p));
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const actorImages=JSON.parse(fs.readFileSync('data/bundle.json','utf8')).actors.flatMap(a=>a.assets.variants.map(i=>i.localPath));
const checks=['app/app.js','app/core.js','app/index.html','app/styles.css','app/updates.css','app/theme.css','app/ta-login.js','app/ta-login.css','app/vendor/jsQR.js','app/vendor/jsQR.LICENSE.txt','app/vendor/msgpack.LICENSE.txt','desktop/main.cjs','desktop/preload.cjs','desktop/ta-codec.cjs','desktop/ta-session.cjs','desktop/official-data.cjs','data/bundle.json','node_modules/@msgpack/msgpack/dist.cjs/decode.cjs',...actorImages].map(p=>{const bytes=asar.extractFile(archive,path.normalize(p));return {path:p,sha256:sha(bytes),matchesSource:sha(bytes)===sha(fs.readFileSync(p))};});
const runtime='release/win-unpacked/resources/ta-runtime',sourceRuntime='release/ta-runtime/atlas-ta-helper';
const walk=dir=>fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(dir,e.name)):[path.join(dir,e.name)]);
const runtimeChecks=walk(sourceRuntime).map(p=>{const relative=path.relative(sourceRuntime,p),installed=path.join(runtime,relative);return {path:relative.replaceAll('\\','/'),sha256:sha(fs.readFileSync(p)),matchesSource:fs.existsSync(installed)&&sha(fs.readFileSync(installed))===sha(fs.readFileSync(p))};});
const manifest=JSON.parse(fs.readFileSync(path.join(runtime,'runtime-manifest.json')));
const protocolChecks=Object.entries(manifest.sources).map(([name,hash])=>({name,matchesSource:sha(fs.readFileSync(path.join('desktop/ta-python',name)))===hash}));
const report={archive,fileEntries:files.length,forbiddenFiles:forbidden,sourceChecks:checks,runtimeChecks,protocolChecks};
fs.writeFileSync('verification/package-audit.json',JSON.stringify(report,null,2));
console.log(JSON.stringify(report));
if(forbidden.length||[...checks,...runtimeChecks,...protocolChecks].some(c=>!c.matchesSource))process.exitCode=1;
